import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [expenseList, setExpenseList] = useState<Expense[]>([]);

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    addExpense(event);
  };

  const addExpense = (event: React.FormEvent<HTMLFormElement>) => {
    const value = getExpenseAmountFieldValue(event);
    if (value === "") return;
    const amount = convertToCurrency(value);
    setExpenseList([...expenseList, { amount }]);
    resetExpenseAmountField(event);
  };

  const convertToCurrency = (value: string) => {
    const amount = parseFloat(value);
    return amount.toLocaleString("en-US", {
      style: "currency",
      currency: "USD",
    });
  };

  const getExpenseAmountFieldValue = (
    event: React.FormEvent<HTMLFormElement>
  ) => {
    return getExpenseAmountField(event).value;
  };

  const resetExpenseAmountField = (event: React.FormEvent<HTMLFormElement>) => {
    getExpenseAmountField(event).value = "";
  };

  const getExpenseAmountField = (event: React.FormEvent<HTMLFormElement>) => {
    return event.currentTarget.querySelector(
      "input#expense-amount"
    ) as HTMLInputElement;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Easy Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.expenseForm}>
          <form onSubmit={handleSubmit}>
            <label htmlFor="expense-amount">Expense amount:</label>
            <input id="expense-amount" type="text" />
            <button type="submit">Add expense</button>
          </form>
        </div>
        <div className={styles.expenseList}>
          <span>Expenses:</span>
          <ul>
            {expenseList.map((expense, index) => (
              <li key={index}>{expense.amount}</li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
};

interface Expense {
  amount: string;
}

export default Home;
